name: list_test
description: "A new Flutter project."
publish_to: 'none' 
version: 1.0.0+1
environment:
  sdk: ^3.10.7

dependencies:
  flutter:
    sdk: flutter
  animated_text_kit: ^4.3.0
  bloc: ^9.2.0
  cupertino_icons: ^1.0.8
  dartz: ^0.10.1
  dio: ^5.9.1
  equatable: ^2.0.8
  flutter_bloc: ^9.1.1
  get_it: ^9.2.0
  http: ^1.6.0
  

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
flutter: 
  uses-material-design: true

  
  
  
  

  
  

  
  

  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
